/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AxiosInstance, AxiosPromise, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';

// @ts-ignore
import {
  BASE_PATH,
  BaseAPI,
  COLLECTION_FORMATS,
  type RequestArgs,
  RequiredError,
  operationServerMap,
} from '../base';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  createRequestFunction,
  serializeDataIfNeeded,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  toPathString,
} from '../common';
import type { Configuration } from '../configuration';
// @ts-ignore
import type { Plugin } from '../models';

/**
 * RootApi - axios parameter creator
 * @export
 */
export const RootApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Get the API version.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getApiVersion: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/app/rest/apiVersion`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as Record<string, string>;
      const localVarQueryParameter = {} as Record<string, string>;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions["headers"] ? baseOptions["headers"] : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options["headers"],
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get the plugin info.
     * @param {string} [fields]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPluginInfo: async (
      fields?: string,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/app/rest/info`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as Record<string, string>;
      const localVarQueryParameter = {} as Record<string, string>;

      if (fields !== undefined) {
        localVarQueryParameter['fields'] = String(fields);
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions["headers"] ? baseOptions["headers"] : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options["headers"],
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get root endpoints.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getRootEndpointsOfRoot: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/app/rest`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as Record<string, string>;
      const localVarQueryParameter = {} as Record<string, string>;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions["headers"] ? baseOptions["headers"] : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options["headers"],
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get the TeamCity server version.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getVersion: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/app/rest/version`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as Record<string, string>;
      const localVarQueryParameter = {} as Record<string, string>;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions["headers"] ? baseOptions["headers"] : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options["headers"],
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * RootApi - functional programming interface
 * @export
 */
export const RootApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = RootApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Get the API version.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getApiVersion(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getApiVersion(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['RootApi.getApiVersion']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Get the plugin info.
     * @param {string} [fields]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getPluginInfo(
      fields?: string,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Plugin>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getPluginInfo(fields, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['RootApi.getPluginInfo']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Get root endpoints.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getRootEndpointsOfRoot(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getRootEndpointsOfRoot(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['RootApi.getRootEndpointsOfRoot']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Get the TeamCity server version.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getVersion(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getVersion(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['RootApi.getVersion']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * RootApi - factory interface
 * @export
 */
export const RootApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = RootApiFp(configuration);
  return {
    /**
     *
     * @summary Get the API version.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getApiVersion(options?: RawAxiosRequestConfig): AxiosPromise<string> {
      return localVarFp.getApiVersion(options).then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Get the plugin info.
     * @param {string} [fields]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPluginInfo(fields?: string, options?: RawAxiosRequestConfig): AxiosPromise<Plugin> {
      return localVarFp.getPluginInfo(fields, options).then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Get root endpoints.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getRootEndpointsOfRoot(options?: RawAxiosRequestConfig): AxiosPromise<string> {
      return localVarFp.getRootEndpointsOfRoot(options).then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Get the TeamCity server version.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getVersion(options?: RawAxiosRequestConfig): AxiosPromise<string> {
      return localVarFp.getVersion(options).then((request) => request(axios, basePath));
    },
  };
};

/**
 * RootApi - interface
 * @export
 * @interface RootApi
 */
export interface RootApiInterface {
  /**
   *
   * @summary Get the API version.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RootApiInterface
   */
  getApiVersion(options?: RawAxiosRequestConfig): AxiosPromise<string>;

  /**
   *
   * @summary Get the plugin info.
   * @param {string} [fields]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RootApiInterface
   */
  getPluginInfo(fields?: string, options?: RawAxiosRequestConfig): AxiosPromise<Plugin>;

  /**
   *
   * @summary Get root endpoints.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RootApiInterface
   */
  getRootEndpointsOfRoot(options?: RawAxiosRequestConfig): AxiosPromise<string>;

  /**
   *
   * @summary Get the TeamCity server version.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RootApiInterface
   */
  getVersion(options?: RawAxiosRequestConfig): AxiosPromise<string>;
}

/**
 * RootApi - object-oriented interface
 * @export
 * @class RootApi
 * @extends {BaseAPI}
 */
export class RootApi extends BaseAPI implements RootApiInterface {
  /**
   *
   * @summary Get the API version.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RootApi
   */
  public getApiVersion(options?: RawAxiosRequestConfig) {
    return RootApiFp(this.configuration)
      .getApiVersion(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get the plugin info.
   * @param {string} [fields]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RootApi
   */
  public getPluginInfo(fields?: string, options?: RawAxiosRequestConfig) {
    return RootApiFp(this.configuration)
      .getPluginInfo(fields, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get root endpoints.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RootApi
   */
  public getRootEndpointsOfRoot(options?: RawAxiosRequestConfig) {
    return RootApiFp(this.configuration)
      .getRootEndpointsOfRoot(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get the TeamCity server version.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RootApi
   */
  public getVersion(options?: RawAxiosRequestConfig) {
    return RootApiFp(this.configuration)
      .getVersion(options)
      .then((request) => request(this.axios, this.basePath));
  }
}
