/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AxiosInstance, AxiosPromise, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';

// @ts-ignore
import {
  BASE_PATH,
  BaseAPI,
  COLLECTION_FORMATS,
  type RequestArgs,
  RequiredError,
  operationServerMap,
} from '../base';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  createRequestFunction,
  serializeDataIfNeeded,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  toPathString,
} from '../common';
import type { Configuration } from '../configuration';
// @ts-ignore
import type { ServerAuthSettings } from '../models';

/**
 * ServerAuthenticationSettingsApi - axios parameter creator
 * @export
 */
export const ServerAuthenticationSettingsApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @summary Get authentication settings.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAuthSettings: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/app/rest/server/authSettings`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as Record<string, string>;
      const localVarQueryParameter = {} as Record<string, string>;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions["headers"] ? baseOptions["headers"] : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options["headers"],
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Set authentication settings.
     * @param {ServerAuthSettings} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    setAuthSettings: async (
      body?: ServerAuthSettings,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/app/rest/server/authSettings`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as Record<string, string>;
      const localVarQueryParameter = {} as Record<string, string>;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions["headers"] ? baseOptions["headers"] : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options["headers"],
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        body,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * ServerAuthenticationSettingsApi - functional programming interface
 * @export
 */
export const ServerAuthenticationSettingsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = ServerAuthenticationSettingsApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Get authentication settings.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getAuthSettings(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ServerAuthSettings>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getAuthSettings(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ServerAuthenticationSettingsApi.getAuthSettings']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Set authentication settings.
     * @param {ServerAuthSettings} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async setAuthSettings(
      body?: ServerAuthSettings,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ServerAuthSettings>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.setAuthSettings(body, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ServerAuthenticationSettingsApi.setAuthSettings']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * ServerAuthenticationSettingsApi - factory interface
 * @export
 */
export const ServerAuthenticationSettingsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = ServerAuthenticationSettingsApiFp(configuration);
  return {
    /**
     *
     * @summary Get authentication settings.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAuthSettings(options?: RawAxiosRequestConfig): AxiosPromise<ServerAuthSettings> {
      return localVarFp.getAuthSettings(options).then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Set authentication settings.
     * @param {ServerAuthSettings} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    setAuthSettings(
      body?: ServerAuthSettings,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ServerAuthSettings> {
      return localVarFp.setAuthSettings(body, options).then((request) => request(axios, basePath));
    },
  };
};

/**
 * ServerAuthenticationSettingsApi - interface
 * @export
 * @interface ServerAuthenticationSettingsApi
 */
export interface ServerAuthenticationSettingsApiInterface {
  /**
   *
   * @summary Get authentication settings.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ServerAuthenticationSettingsApiInterface
   */
  getAuthSettings(options?: RawAxiosRequestConfig): AxiosPromise<ServerAuthSettings>;

  /**
   *
   * @summary Set authentication settings.
   * @param {ServerAuthSettings} [body]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ServerAuthenticationSettingsApiInterface
   */
  setAuthSettings(
    body?: ServerAuthSettings,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<ServerAuthSettings>;
}

/**
 * ServerAuthenticationSettingsApi - object-oriented interface
 * @export
 * @class ServerAuthenticationSettingsApi
 * @extends {BaseAPI}
 */
export class ServerAuthenticationSettingsApi
  extends BaseAPI
  implements ServerAuthenticationSettingsApiInterface
{
  /**
   *
   * @summary Get authentication settings.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ServerAuthenticationSettingsApi
   */
  public getAuthSettings(options?: RawAxiosRequestConfig) {
    return ServerAuthenticationSettingsApiFp(this.configuration)
      .getAuthSettings(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Set authentication settings.
   * @param {ServerAuthSettings} [body]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ServerAuthenticationSettingsApi
   */
  public setAuthSettings(body?: ServerAuthSettings, options?: RawAxiosRequestConfig) {
    return ServerAuthenticationSettingsApiFp(this.configuration)
      .setAuthSettings(body, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
