/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { AgentRequirement } from './agent-requirement';

/**
 * Represents a list of AgentRequirement entities.
 * @export
 * @interface AgentRequirements
 */
export interface AgentRequirements {
  /**
   * The number of `agent-requirement` objects in this collection.
   * @type {number}
   * @memberof AgentRequirements
   */
  count?: number;
  /**
   * The list of `agent-requirement` objects owned by this collection.
   * @type {Array<AgentRequirement>}
   * @memberof AgentRequirements
   */
  'agent-requirement'?: Array<AgentRequirement>;
}
