/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents a locator string for filtering AgentPool entities.
 * @export
 * @interface AgentPoolLocator
 */
export interface AgentPoolLocator {
  /**
   * Agent pool id.
   * @type {number}
   * @memberof AgentPoolLocator
   */
  $singleValue?: number;
  /**
   * Pool\'s associated agents locator.
   * @type {string}
   * @memberof AgentPoolLocator
   */
  agent?: string;
  /**
   * For paginated calls, how many entities to return per page.
   * @type {number}
   * @memberof AgentPoolLocator
   */
  count?: number;
  /**
   * Agent pool id.
   * @type {number}
   * @memberof AgentPoolLocator
   */
  id?: number;
  /**
   * Agent pool name.
   * @type {string}
   * @memberof AgentPoolLocator
   */
  name?: string;
  /**
   * Pool\'s associated projects locator.
   * @type {string}
   * @memberof AgentPoolLocator
   */
  project?: string;
  /**
   * For paginated calls, from which entity to start rendering the page.
   * @type {number}
   * @memberof AgentPoolLocator
   */
  start?: number;
}
