/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A build that cannot start until explicitly approved by designated team members. See the [Build approval](https://www.jetbrains.com/help/teamcity/build-approval.html) build feature and [Untrusted Builds](https://www.jetbrains.com/help/teamcity/untrusted-builds.html) project settings for more information. Send a `POST` request to the `/app/rest/buildQueue/{buildLocator}/approve` endpoint to manually approve a build.
 * @export
 * @interface ApprovableBuild
 */
export interface ApprovableBuild {
  /**
   * The ID of a build that requires manual approval.
   * @type {string}
   * @memberof ApprovableBuild
   */
  buildId?: string;
  /**
   * The ID of a build configuration that spawned this approvable build.
   * @type {string}
   * @memberof ApprovableBuild
   */
  buildTypeId?: string;
  /**
   * The name of a build configuration that spawned this approvable build.
   * @type {string}
   * @memberof ApprovableBuild
   */
  buildTypeName?: string;
}
