/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { ArtifactDependency } from './artifact-dependency';

/**
 * Represents a list of ArtifactDependency entities.
 * @export
 * @interface ArtifactDependencies
 */
export interface ArtifactDependencies {
  /**
   * The number of `artifact_dependency` objects in this collection.
   * @type {number}
   * @memberof ArtifactDependencies
   */
  count?: number;
  /**
   * The list of `artifact_dependency` objects owned by this collection.
   * @type {Array<ArtifactDependency>}
   * @memberof ArtifactDependencies
   */
  'artifact-dependency'?: Array<ArtifactDependency>;
  /**
   *
   * @type {string}
   * @memberof ArtifactDependencies
   */
  replace?: string;
}
