/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { AuditAction } from './audit-action';
// May contain unused imports in some cases
// @ts-ignore
import type { RelatedEntities } from './related-entities';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

/**
 * An audit event that stores information about all meaningful actions performed by every TeamCity user.
 * @export
 * @interface AuditEvent
 */
export interface AuditEvent {
  /**
   * The automatically generated unique ID of the event.
   * @type {string}
   * @memberof AuditEvent
   */
  id?: string;
  /**
   * The time of the logged event.
   * @type {string}
   * @memberof AuditEvent
   */
  timestamp?: string;
  /**
   * The event summary that briefly explains its essence. Certain events (such as starting a build) have no comment attached.
   * @type {string}
   * @memberof AuditEvent
   */
  comment?: string;
  /**
   *
   * @type {AuditAction}
   * @memberof AuditEvent
   */
  action?: AuditAction;
  /**
   *
   * @type {RelatedEntities}
   * @memberof AuditEvent
   */
  relatedEntities?: RelatedEntities;
  /**
   *
   * @type {User}
   * @memberof AuditEvent
   */
  user?: User;
}
