/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { AuditEvent } from './audit-event';

/**
 * Represents a paginated list of AuditEvent entities.
 * @export
 * @interface AuditEvents
 */
export interface AuditEvents {
  /**
   * The current number of AuditEvent objects in this list.
   * @type {number}
   * @memberof AuditEvents
   */
  count?: number;
  /**
   * If the list of returned entities exceeds the request `count` value, TeamCity splits it into multiple batches. This property returns the endpoint that allows you to obtain the next batch.
   * @type {string}
   * @memberof AuditEvents
   */
  nextHref?: string;
  /**
   * If the list of returned entities exceeds the request `count` value, TeamCity splits it into multiple batches. This property returns the endpoint that allows you to obtain the previous batch.
   * @type {string}
   * @memberof AuditEvents
   */
  prevHref?: string;
  /**
   * The relative link (without the server URL) used to retrieve this object.
   * @type {string}
   * @memberof AuditEvents
   */
  href?: string;
  /**
   * The list of audit events owned by this collection that satisfy the given locator.
   * @type {Array<AuditEvent>}
   * @memberof AuditEvents
   */
  auditEvent?: Array<AuditEvent>;
}
