/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { Comment } from './comment';

/**
 * Contains information about agent authorization state. Send AuthorizedInfo objects to the [`/app/rest/agents/{agentLocator}/authorizedInfo`](https://www.jetbrains.com/help/teamcity/rest/agentapi.html#setAuthorizedInfo) endpoint via `PUT` requests to manually authorize and unauthorize agents.
 * @export
 * @interface AuthorizedInfo
 */
export interface AuthorizedInfo {
  /**
   * Returns *true* if the current object state is enabled (for example, pinned for build `PinInfo` or authorized for agent `AuthorizedInfo`; otherwise, *false*.
   * @type {boolean}
   * @memberof AuthorizedInfo
   */
  status?: boolean;
  /**
   *
   * @type {Comment}
   * @memberof AuthorizedInfo
   */
  comment?: Comment;
}
