/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { Branch } from './branch';

/**
 * Represents a list of Branch entities.
 * @export
 * @interface Branches
 */
export interface Branches {
  /**
   * The current number of Branch objects in this list.
   * @type {number}
   * @memberof Branches
   */
  count?: number;
  /**
   * The relative link (without the server URL) used to retrieve this object.
   * @type {string}
   * @memberof Branches
   */
  href?: string;
  /**
   * The list of branches owned by this collection that satisfy the given locator.
   * @type {Array<Branch>}
   * @memberof Branches
   */
  branch?: Array<Branch>;
}
