/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Send a POST request with this object as a payload to cancel a queued (the `/app/rest/buildQueue/<queuedBuildLocator>` endpoint)or already running (the `/app/rest/builds/<buildLocator>` endpoint) build.
 * @export
 * @interface BuildCancelRequest
 */
export interface BuildCancelRequest {
  /**
   * A note that explains why this build was canceled. This note will be written to the canceled build\'s `build.canceledInfo.text` property.
   * @type {string}
   * @memberof BuildCancelRequest
   */
  comment?: string;
  /**
   * If *true*, a new identical build will be queued as soon as the current build is canceled. If *false*, a build will simply be canceled. Similarly to TeamCity UI, the option to re-queue a build is only available if this build is already running. Builds that are still queued can be only aborted.
   * @type {boolean}
   * @memberof BuildCancelRequest
   */
  readdIntoQueue?: boolean;
}
