/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents a locator string for filtering Build entities.
 * @export
 * @interface BuildQueueLocator
 */
export interface BuildQueueLocator {
  /**
   * Agent locator.
   * @type {string}
   * @memberof BuildQueueLocator
   */
  agent?: string;
  /**
   * Build type locator.
   * @type {string}
   * @memberof BuildQueueLocator
   */
  buildType?: string;
  /**
   * For paginated calls, how many entities to return per page.
   * @type {number}
   * @memberof BuildQueueLocator
   */
  count?: number;
  /**
   * Entity ID.
   * @type {string}
   * @memberof BuildQueueLocator
   */
  id?: string;
  /**
   * Supply multiple locators and return a union of the results.
   * @type {string}
   * @memberof BuildQueueLocator
   */
  item?: string;
  /**
   * Is personal.
   * @type {boolean}
   * @memberof BuildQueueLocator
   */
  personal?: boolean;
  /**
   * Agent pool locator.
   * @type {string}
   * @memberof BuildQueueLocator
   */
  pool?: string;
  /**
   * Project locator.
   * @type {string}
   * @memberof BuildQueueLocator
   */
  project?: string;
  /**
   * For paginated calls, from which entity to start rendering the page.
   * @type {number}
   * @memberof BuildQueueLocator
   */
  start?: number;
  /**
   * Deprecated.
   * @type {string}
   * @memberof BuildQueueLocator
   */
  taskId?: string;
  /**
   * User locator.
   * @type {string}
   * @memberof BuildQueueLocator
   */
  user?: string;
}
