/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents an executor of a build.
 * @export
 * @interface BuildExecutor
 */
export interface BuildExecutor {
  /**
   * The name of an external executor that processed this build.
   * @type {string}
   * @memberof BuildExecutor
   */
  name?: string;
}
