/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { ApprovableBuild } from './approvable-build';

/**
 * Stores builds that cannot be started without an explicit approval, along with reasons why these builds require an approval.
 * @export
 * @interface BuildsWithReason
 */
export interface BuildsWithReason {
  /**
   * The list of builds that cannot start without an approval.
   * @type {Array<ApprovableBuild>}
   * @memberof BuildsWithReason
   */
  builds?: Array<ApprovableBuild>;
  /**
   *
   * @type {ApprovableBuild}
   * @memberof BuildsWithReason
   */
  approvalReason?: ApprovableBuild;
}
