/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { Properties } from './properties';

/**
 * Passed to the `Trigger.buildCustomization` property to trigger a customized build.
 * @export
 * @interface BuildTriggerCustomization
 */
export interface BuildTriggerCustomization {
  /**
   * Returns **true** if the agent should clear the build checkout directory before checking out sources from the VCS; otherwise, **false**.
   * @type {boolean}
   * @memberof BuildTriggerCustomization
   */
  enforceCleanCheckout?: boolean;
  /**
   * Returns **true** if the `enforceCleanCheckout` behavior should all apply to all snapshot dependencies of this build; otherwise, **false**.
   * @type {boolean}
   * @memberof BuildTriggerCustomization
   */
  enforceCleanCheckoutForDependencies?: boolean;
  /**
   *
   * @type {Properties}
   * @memberof BuildTriggerCustomization
   */
  parameters?: Properties;
}
