/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Send instances of this class to the `/app/rest/builds/<locator>/status` endpoint to change the status of a build to either \'SUCCESS\' or \'FAILURE\'. This replicates the *Mark as failed...* and *Mark as successful...* operations available from the \'Actions\' menu on the build results page in TeamCity UI.
 * @export
 * @interface BuildStatusUpdate
 */
export interface BuildStatusUpdate {
  /**
   * Set to either \'FAILURE\' or \'SUCCESS\'.
   * @type {string}
   * @memberof BuildStatusUpdate
   */
  status?: string;
  /**
   * Your custom note that explains why the build status was manually changed.
   * @type {string}
   * @memberof BuildStatusUpdate
   */
  comment?: string;
}
