/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { Change } from './change';

/**
 * Represents a paginated list of Change entities.
 * @export
 * @interface Changes
 */
export interface Changes {
  /**
   * The list of Change objects owned by this collection.
   * @type {Array<Change>}
   * @memberof Changes
   */
  change?: Array<Change>;
  /**
   * The relative link (without the server URL) used to retrieve this object.
   * @type {string}
   * @memberof Changes
   */
  href?: string;
  /**
   * If the list of returned entities exceeds the request `count` value, TeamCity splits it into multiple batches. This property returns the endpoint that allows you to obtain the next batch.
   * @type {string}
   * @memberof Changes
   */
  nextHref?: string;
  /**
   * If the list of returned entities exceeds the request `count` value, TeamCity splits it into multiple batches. This property returns the endpoint that allows you to obtain the previous batch.
   * @type {string}
   * @memberof Changes
   */
  prevHref?: string;
  /**
   * The number of Change objects owned by this collection.
   * @type {number}
   * @memberof Changes
   */
  count?: number;
}
