/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { Cron } from './cron';
// May contain unused imports in some cases
// @ts-ignore
import type { Daily } from './daily';

/**
 * Stores current settings according to which the TeamCity performs periodic clean-ups. Use the `/app/rest/server/cleanup` endpoint to view and edit these settings.
 * @export
 * @interface Cleanup
 */
export interface Cleanup {
  /**
   * **true** if the periodic clean-up is enabled; otherwise, **false**.
   * @type {boolean}
   * @memberof Cleanup
   */
  enabled?: boolean;
  /**
   * The maximum clean-up duration (in munutes). If a clean-up exceeds this limit, TeamCity will automatically abort it.
   * @type {number}
   * @memberof Cleanup
   */
  maxCleanupDuration?: number;
  /**
   *
   * @type {Daily}
   * @memberof Cleanup
   */
  daily?: Daily;
  /**
   *
   * @type {Cron}
   * @memberof Cleanup
   */
  cron?: Cron;
}
