/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents a locator string for filtering CloudProfile entities.
 * @export
 * @interface CloudProfileLocator
 */
export interface CloudProfileLocator {
  /**
   * Projects where the cloud profiles are accessible
   * @type {string}
   * @memberof CloudProfileLocator
   */
  affectedProject?: string;
  /**
   * Profile cloud provider id.
   * @type {string}
   * @memberof CloudProfileLocator
   */
  cloudProviderId?: string;
  /**
   * For paginated calls, how many entities to return per page.
   * @type {number}
   * @memberof CloudProfileLocator
   */
  count?: number;
  /**
   * Profile id.
   * @type {string}
   * @memberof CloudProfileLocator
   */
  id?: string;
  /**
   * Cloud image which belongs to a profile.
   * @type {string}
   * @memberof CloudProfileLocator
   */
  image?: string;
  /**
   * Cloud instance which belongs to a profile.
   * @type {string}
   * @memberof CloudProfileLocator
   */
  instance?: string;
  /**
   * Profile name.
   * @type {string}
   * @memberof CloudProfileLocator
   */
  name?: string;
  /**
   * Projects defining the cloud profiles.
   * @type {string}
   * @memberof CloudProfileLocator
   */
  project?: string;
  /**
   *
   * @type {string}
   * @memberof CloudProfileLocator
   */
  property?: string;
  /**
   * For paginated calls, from which entity to start rendering the page.
   * @type {number}
   * @memberof CloudProfileLocator
   */
  start?: number;
}
