/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { CloudImage } from './cloud-image';

/**
 * Represents a paginated list of CloudImage entities.
 * @export
 * @interface CloudImages
 */
export interface CloudImages {
  /**
   * The list of cloud images owned by this collection.
   * @type {Array<CloudImage>}
   * @memberof CloudImages
   */
  cloudImage?: Array<CloudImage>;
  /**
   * The number of cloud images in this collection.
   * @type {number}
   * @memberof CloudImages
   */
  count?: number;
  /**
   * If the list of returned entities exceeds the request `count` value, TeamCity splits it into multiple batches. This property returns the endpoint that allows you to obtain the next batch.
   * @type {string}
   * @memberof CloudImages
   */
  nextHref?: string;
  /**
   * If the list of returned entities exceeds the request `count` value, TeamCity splits it into multiple batches. This property returns the endpoint that allows you to obtain the previous batch.
   * @type {string}
   * @memberof CloudImages
   */
  prevHref?: string;
  /**
   * The relative link (without the server URL) used to retrieve this object.
   * @type {string}
   * @memberof CloudImages
   */
  href?: string;
}
