/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { CloudInstance } from './cloud-instance';

/**
 * Represents a paginated list of CloudInstance entities.
 * @export
 * @interface CloudInstances
 */
export interface CloudInstances {
  /**
   * The number of CloudInstance objects in this collection.
   * @type {number}
   * @memberof CloudInstances
   */
  count?: number;
  /**
   * If the list of returned entities exceeds the request `count` value, TeamCity splits it into multiple batches. This property returns the endpoint that allows you to obtain the next batch.
   * @type {string}
   * @memberof CloudInstances
   */
  nextHref?: string;
  /**
   * If the list of returned entities exceeds the request `count` value, TeamCity splits it into multiple batches. This property returns the endpoint that allows you to obtain the previous batch.
   * @type {string}
   * @memberof CloudInstances
   */
  prevHref?: string;
  /**
   * The relative link (without the TeamCity server URL) used to retrieve this object.
   * @type {string}
   * @memberof CloudInstances
   */
  href?: string;
  /**
   * The list of CloudInstance objects owned by this collection.
   * @type {Array<CloudInstance>}
   * @memberof CloudInstances
   */
  cloudInstance?: Array<CloudInstance>;
}
