/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { Users } from './users';

/**
 * An author of a change committed to a VCS repository.
 * @export
 * @interface Commiter
 */
export interface Commiter {
  /**
   * The VCS username of a change author.
   * @type {string}
   * @memberof Commiter
   */
  vcsUsername?: string;
  /**
   *
   * @type {Users}
   * @memberof Commiter
   */
  users?: Users;
}
