/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { Group } from './group';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';
// May contain unused imports in some cases
// @ts-ignore
import type { Users } from './users';

/**
 * Represents composite approval rule(combines multiple groups and users) and its current status for the given build.
 * @export
 * @interface CompositeApprovalRule
 */
export interface CompositeApprovalRule {
  /**
   *
   * @type {Array<User>}
   * @memberof CompositeApprovalRule
   */
  users?: Array<User>;
  /**
   *
   * @type {Users}
   * @memberof CompositeApprovalRule
   */
  currentlyApprovedBy?: Users;
  /**
   *
   * @type {number}
   * @memberof CompositeApprovalRule
   */
  requiredApprovalsCount?: number;
  /**
   *
   * @type {Array<Group>}
   * @memberof CompositeApprovalRule
   */
  groups?: Array<Group>;
}
