/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents a locator string for filtering DeploymentDashboard entities.
 * @export
 * @interface DeploymentDashboardLocator
 */
export interface DeploymentDashboardLocator {
  /**
   * Projects where the deployment dashboards are accessible.
   * @type {string}
   * @memberof DeploymentDashboardLocator
   */
  affectedProject?: string;
  /**
   * For paginated calls, how many entities to return per page.
   * @type {number}
   * @memberof DeploymentDashboardLocator
   */
  count?: number;
  /**
   * Dashboard id.
   * @type {string}
   * @memberof DeploymentDashboardLocator
   */
  id?: string;
  /**
   * Dashboard name.
   * @type {string}
   * @memberof DeploymentDashboardLocator
   */
  name?: string;
  /**
   * Projects defining the deployment dashboards.
   * @type {string}
   * @memberof DeploymentDashboardLocator
   */
  project?: string;
  /**
   * For paginated calls, from which entity to start rendering the page.
   * @type {number}
   * @memberof DeploymentDashboardLocator
   */
  start?: number;
}
