/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { DeploymentHistory } from './deployment-history';
// May contain unused imports in some cases
// @ts-ignore
import type { DeploymentStateEntry } from './deployment-state-entry';

/**
 * Represents a list of DeploymentStateEntry entities.
 * @export
 * @interface DeploymentStateEntries
 */
export interface DeploymentStateEntries {
  /**
   *
   * @type {number}
   * @memberof DeploymentStateEntries
   */
  count?: number;
  /**
   *
   * @type {DeploymentHistory}
   * @memberof DeploymentStateEntries
   */
  historyFromPosted?: DeploymentHistory;
  /**
   *
   * @type {Array<DeploymentStateEntry>}
   * @memberof DeploymentStateEntries
   */
  deploymentStateEntry?: Array<DeploymentStateEntry>;
}
