/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { Entry } from './entry';

/**
 * Represents a list of Entry entities.
 * @export
 * @interface Entries
 */
export interface Entries {
  /**
   *
   * @type {number}
   * @memberof Entries
   */
  count?: number;
  /**
   *
   * @type {Array<Entry>}
   * @memberof Entries
   */
  entry?: Array<Entry>;
}
