/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents a list of File entities.
 * @export
 * @interface Files
 */
export interface Files {
  /**
   * The number of File objects in this collection.
   * @type {number}
   * @memberof Files
   */
  count?: number;
  /**
   * The relative (without TeamCity server URL) link to this collection.
   * @type {string}
   * @memberof Files
   */
  href?: string;
  /**
   * The list of File objects owned by this collection.
   * @type {Array<any>}
   * @memberof Files
   */
  file?: Array<any>;
}
