/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { HealthCategory } from './health-category';

/**
 * Represents a paginated list of HealthCategory entities.
 * @export
 * @interface HealthCategories
 */
export interface HealthCategories {
  /**
   *
   * @type {number}
   * @memberof HealthCategories
   */
  count?: number;
  /**
   *
   * @type {Array<HealthCategory>}
   * @memberof HealthCategories
   */
  healthCategory?: Array<HealthCategory>;
  /**
   *
   * @type {string}
   * @memberof HealthCategories
   */
  href?: string;
  /**
   *
   * @type {string}
   * @memberof HealthCategories
   */
  nextHref?: string;
  /**
   *
   * @type {string}
   * @memberof HealthCategories
   */
  prevHref?: string;
}
