/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { HealthItem } from './health-item';

/**
 * Represents a paginated list of HealthItem entities.
 * @export
 * @interface HealthStatusItems
 */
export interface HealthStatusItems {
  /**
   *
   * @type {number}
   * @memberof HealthStatusItems
   */
  count?: number;
  /**
   *
   * @type {Array<HealthItem>}
   * @memberof HealthStatusItems
   */
  healthItem?: Array<HealthItem>;
  /**
   *
   * @type {string}
   * @memberof HealthStatusItems
   */
  href?: string;
  /**
   *
   * @type {string}
   * @memberof HealthStatusItems
   */
  nextHref?: string;
  /**
   *
   * @type {string}
   * @memberof HealthStatusItems
   */
  prevHref?: string;
}
