/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { MatrixParameterDescriptor } from './matrix-parameter-descriptor';

/**
 *
 * @export
 * @interface MatrixBuildFeatureDescriptor
 */
export interface MatrixBuildFeatureDescriptor {
  /**
   *
   * @type {boolean}
   * @memberof MatrixBuildFeatureDescriptor
   */
  separateArtifacts?: boolean;
  /**
   *
   * @type {string}
   * @memberof MatrixBuildFeatureDescriptor
   */
  id?: string;
  /**
   *
   * @type {number}
   * @memberof MatrixBuildFeatureDescriptor
   */
  count?: number;
  /**
   *
   * @type {Array<MatrixParameterDescriptor>}
   * @memberof MatrixBuildFeatureDescriptor
   */
  parameters?: Array<MatrixParameterDescriptor>;
}
