/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { Entries } from './entries';

/**
 * Represents a named Entries entity.
 * @export
 * @interface MetaData
 */
export interface MetaData {
  /**
   *
   * @type {string}
   * @memberof MetaData
   */
  id?: string;
  /**
   *
   * @type {Entries}
   * @memberof MetaData
   */
  entries?: Entries;
}
