/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { Files } from './files';
// May contain unused imports in some cases
// @ts-ignore
import type { Href } from './href';

/**
 * A file or a directory associated with, for instance, a published artifact.
 * @export
 * @interface ModelFile
 */
export interface ModelFile {
  /**
   * The public file name.
   * @type {string}
   * @memberof ModelFile
   */
  name?: string;
  /**
   * The full name of a file, including all special characters omitted in the `name` property. Can be equal to `name`.
   * @type {string}
   * @memberof ModelFile
   */
  fullName?: string;
  /**
   * The file size in bytes.
   * @type {number}
   * @memberof ModelFile
   */
  size?: number;
  /**
   * Returns the last time this file was edited.
   * @type {string}
   * @memberof ModelFile
   */
  modificationTime?: string;
  /**
   * The link to file metadata object.
   * @type {string}
   * @memberof ModelFile
   */
  href?: string;
  /**
   *
   * @type {ModelFile}
   * @memberof ModelFile
   */
  parent?: ModelFile;
  /**
   *
   * @type {Href}
   * @memberof ModelFile
   */
  content?: Href;
  /**
   *
   * @type {Files}
   * @memberof ModelFile
   */
  children?: Files;
}
