/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { Mute } from './mute';

/**
 * Represents a paginated list of Mute entities.
 * @export
 * @interface Mutes
 */
export interface Mutes {
  /**
   *
   * @type {number}
   * @memberof Mutes
   */
  count?: number;
  /**
   *
   * @type {string}
   * @memberof Mutes
   */
  nextHref?: string;
  /**
   *
   * @type {string}
   * @memberof Mutes
   */
  prevHref?: string;
  /**
   *
   * @type {string}
   * @memberof Mutes
   */
  href?: string;
  /**
   *
   * @type {Array<Mute>}
   * @memberof Mutes
   */
  mute?: Array<Mute>;
}
