/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { DisabledResponsibilities } from './disabled-responsibilities';
// May contain unused imports in some cases
// @ts-ignore
import type { EffectiveResponsibilities } from './effective-responsibilities';
// May contain unused imports in some cases
// @ts-ignore
import type { EnabledResponsibilities } from './enabled-responsibilities';

/**
 * Represents a TeamCity node.
 * @export
 * @interface Node
 */
export interface Node {
  /**
   *
   * @type {string}
   * @memberof Node
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof Node
   */
  url?: string;
  /**
   *
   * @type {string}
   * @memberof Node
   */
  state?: NodeStateEnum;
  /**
   *
   * @type {string}
   * @memberof Node
   */
  role?: string;
  /**
   *
   * @type {boolean}
   * @memberof Node
   */
  current?: boolean;
  /**
   *
   * @type {EnabledResponsibilities}
   * @memberof Node
   */
  enabledResponsibilities?: EnabledResponsibilities;
  /**
   *
   * @type {DisabledResponsibilities}
   * @memberof Node
   */
  disabledResponsibilities?: DisabledResponsibilities;
  /**
   *
   * @type {EffectiveResponsibilities}
   * @memberof Node
   */
  effectiveResponsibilities?: EffectiveResponsibilities;
}

export const NodeStateEnum = {
  Online: 'online',
  Offline: 'offline',
  Stopping: 'stopping',
  Starting: 'starting',
} as const;

export type NodeStateEnum = (typeof NodeStateEnum)[keyof typeof NodeStateEnum];
