/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { Agent } from './agent';
// May contain unused imports in some cases
// @ts-ignore
import type { AgentPool } from './agent-pool';
// May contain unused imports in some cases
// @ts-ignore
import type { Build } from './build';
// May contain unused imports in some cases
// @ts-ignore
import type { BuildType } from './build-type';
// May contain unused imports in some cases
// @ts-ignore
import type { Change } from './change';
// May contain unused imports in some cases
// @ts-ignore
import type { Group } from './group';
// May contain unused imports in some cases
// @ts-ignore
import type { Problem } from './problem';
// May contain unused imports in some cases
// @ts-ignore
import type { Project } from './project';
// May contain unused imports in some cases
// @ts-ignore
import type { Test } from './test';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';
// May contain unused imports in some cases
// @ts-ignore
import type { VcsRoot } from './vcs-root';

/**
 * Represents a related entity.
 * @export
 * @interface RelatedEntity
 */
export interface RelatedEntity {
  /**
   *
   * @type {string}
   * @memberof RelatedEntity
   */
  type?: string;
  /**
   *
   * @type {boolean}
   * @memberof RelatedEntity
   */
  unknown?: boolean;
  /**
   *
   * @type {string}
   * @memberof RelatedEntity
   */
  internalId?: string;
  /**
   *
   * @type {string}
   * @memberof RelatedEntity
   */
  text?: string;
  /**
   *
   * @type {Build}
   * @memberof RelatedEntity
   */
  build?: Build;
  /**
   *
   * @type {BuildType}
   * @memberof RelatedEntity
   */
  buildType?: BuildType;
  /**
   *
   * @type {Project}
   * @memberof RelatedEntity
   */
  project?: Project;
  /**
   *
   * @type {User}
   * @memberof RelatedEntity
   */
  user?: User;
  /**
   *
   * @type {Group}
   * @memberof RelatedEntity
   */
  group?: Group;
  /**
   *
   * @type {Test}
   * @memberof RelatedEntity
   */
  test?: Test;
  /**
   *
   * @type {Problem}
   * @memberof RelatedEntity
   */
  problem?: Problem;
  /**
   *
   * @type {Agent}
   * @memberof RelatedEntity
   */
  agent?: Agent;
  /**
   *
   * @type {VcsRoot}
   * @memberof RelatedEntity
   */
  vcsRoot?: VcsRoot;
  /**
   *
   * @type {Change}
   * @memberof RelatedEntity
   */
  change?: Change;
  /**
   *
   * @type {AgentPool}
   * @memberof RelatedEntity
   */
  agentPool?: AgentPool;
}
