/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { BranchVersion } from './branch-version';

/**
 * Represents the list of the repository Branch entities with their recent revisions.
 * @export
 * @interface RepositoryState
 */
export interface RepositoryState {
  /**
   * Specifies when this RepositoryState object was created.
   * @type {string}
   * @memberof RepositoryState
   */
  timestamp?: string;
  /**
   * The length of the `branches` collection.
   * @type {number}
   * @memberof RepositoryState
   */
  count?: number;
  /**
   * The list of repository branches.
   * @type {Array<BranchVersion>}
   * @memberof RepositoryState
   */
  branch?: Array<BranchVersion>;
}
