/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The list of unmet requirements that prevents an agent to run the target build. Most commongly used in [`Compatibility`](https://www.jetbrains.com/help/teamcity/rest/compatibility.html) objects.
 * @export
 * @interface Requirements
 */
export interface Requirements {
  /**
   * The summary of all unment requirements that make the target agent incompatible with the given configuration.
   * @type {string}
   * @memberof Requirements
   */
  description?: string;
}
