/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents an investigation resolution timestamp and details.
 * @export
 * @interface Resolution
 */
export interface Resolution {
  /**
   *
   * @type {string}
   * @memberof Resolution
   */
  type?: ResolutionTypeEnum;
  /**
   *
   * @type {string}
   * @memberof Resolution
   */
  time?: string;
}

export const ResolutionTypeEnum = {
  Manually: 'manually',
  WhenFixed: 'whenFixed',
  AtTime: 'atTime',
} as const;

export type ResolutionTypeEnum = (typeof ResolutionTypeEnum)[keyof typeof ResolutionTypeEnum];
