/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents a locator string for filtering Tag entities.
 * @export
 * @interface TagLocator
 */
export interface TagLocator {
  /**
   *
   * @type {string}
   * @memberof TagLocator
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof TagLocator
   */
  owner?: string;
  /**
   *
   * @type {string}
   * @memberof TagLocator
   */
  private?: string;
}
