/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents a test results counter (how many times this test was successful/failed/muted/ignored).
 * @export
 * @interface TestCounters
 */
export interface TestCounters {
  /**
   *
   * @type {number}
   * @memberof TestCounters
   */
  ignored?: number;
  /**
   *
   * @type {number}
   * @memberof TestCounters
   */
  failed?: number;
  /**
   *
   * @type {number}
   * @memberof TestCounters
   */
  muted?: number;
  /**
   *
   * @type {number}
   * @memberof TestCounters
   */
  success?: number;
  /**
   *
   * @type {number}
   * @memberof TestCounters
   */
  all?: number;
  /**
   *
   * @type {number}
   * @memberof TestCounters
   */
  newFailed?: number;
  /**
   *
   * @type {number}
   * @memberof TestCounters
   */
  duration?: number;
}
