/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { TestCounters } from './test-counters';
// May contain unused imports in some cases
// @ts-ignore
import type { TestOccurrence } from './test-occurrence';

/**
 * Represents a paginated list of TestOccurrence entities.
 * @export
 * @interface TestOccurrences
 */
export interface TestOccurrences {
  /**
   *
   * @type {number}
   * @memberof TestOccurrences
   */
  count?: number;
  /**
   *
   * @type {string}
   * @memberof TestOccurrences
   */
  href?: string;
  /**
   *
   * @type {string}
   * @memberof TestOccurrences
   */
  nextHref?: string;
  /**
   *
   * @type {string}
   * @memberof TestOccurrences
   */
  prevHref?: string;
  /**
   *
   * @type {Array<TestOccurrence>}
   * @memberof TestOccurrences
   */
  testOccurrence?: Array<TestOccurrence>;
  /**
   *
   * @type {TestCounters}
   * @memberof TestOccurrences
   */
  testCounters?: TestCounters;
  /**
   *
   * @type {number}
   * @memberof TestOccurrences
   */
  ignored?: number;
  /**
   *
   * @type {number}
   * @memberof TestOccurrences
   */
  failed?: number;
  /**
   *
   * @type {number}
   * @memberof TestOccurrences
   */
  passed?: number;
  /**
   *
   * @type {number}
   * @memberof TestOccurrences
   */
  newFailed?: number;
  /**
   *
   * @type {number}
   * @memberof TestOccurrences
   */
  muted?: number;
}
