/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { UserApprovalRule } from './user-approval-rule';

/**
 * Represents a list of UserApprovalRule entities.
 * @export
 * @interface UserApprovals
 */
export interface UserApprovals {
  /**
   * The number of UserApprovalRule objects in this collection.
   * @type {number}
   * @memberof UserApprovals
   */
  count?: number;
  /**
   * The list of UserApprovalRule stored in this collection.
   * @type {Array<UserApprovalRule>}
   * @memberof UserApprovals
   */
  userApproval?: Array<UserApprovalRule>;
}
