/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { Groups } from './groups';
// May contain unused imports in some cases
// @ts-ignore
import type { Properties } from './properties';
// May contain unused imports in some cases
// @ts-ignore
import type { Roles } from './roles';
// May contain unused imports in some cases
// @ts-ignore
import type { UserAvatars } from './user-avatars';

/**
 * Represents a user.
 * @export
 * @interface User
 */
export interface User {
  /**
   *
   * @type {string}
   * @memberof User
   */
  username?: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  name?: string;
  /**
   *
   * @type {number}
   * @memberof User
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof User
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  lastLogin?: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  password?: string;
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  hasPassword?: boolean;
  /**
   *
   * @type {string}
   * @memberof User
   */
  realm?: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  href?: string;
  /**
   *
   * @type {Properties}
   * @memberof User
   */
  properties?: Properties;
  /**
   *
   * @type {Roles}
   * @memberof User
   */
  roles?: Roles;
  /**
   *
   * @type {Groups}
   * @memberof User
   */
  groups?: Groups;
  /**
   *
   * @type {string}
   * @memberof User
   */
  locator?: string;
  /**
   *
   * @type {UserAvatars}
   * @memberof User
   */
  avatars?: UserAvatars;
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  enabled2FA?: boolean;
}
