/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents a locator string for filtering User entities.
 * @export
 * @interface UserLocator
 */
export interface UserLocator {
  /**
   * Username or \'current\' for current user.
   * @type {string}
   * @memberof UserLocator
   */
  $singleValue?: string;
  /**
   * User group (direct or indirect parent) locator, includes the user considering group hierarchy.
   * @type {string}
   * @memberof UserLocator
   */
  affectedGroup?: string;
  /**
   * For paginated calls, how many entities to return per page.
   * @type {number}
   * @memberof UserLocator
   */
  count?: number;
  /**
   * User email.
   * @type {string}
   * @memberof UserLocator
   */
  email?: string;
  /**
   * User group (direct parent) locator, includes the user directly.
   * @type {string}
   * @memberof UserLocator
   */
  group?: string;
  /**
   * User id.
   * @type {number}
   * @memberof UserLocator
   */
  id?: number;
  /**
   * User\'s last login time formatted as \'yyyyMMddTHHmmss+ZZZZ\'
   * @type {string}
   * @memberof UserLocator
   */
  lastLogin?: string;
  /**
   * User\'s display name
   * @type {string}
   * @memberof UserLocator
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof UserLocator
   */
  property?: string;
  /**
   * User\'s role
   * @type {string}
   * @memberof UserLocator
   */
  role?: string;
  /**
   * For paginated calls, from which entity to start rendering the page.
   * @type {number}
   * @memberof UserLocator
   */
  start?: number;
  /**
   * Username of a user.
   * @type {string}
   * @memberof UserLocator
   */
  username?: string;
}
