/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents a group of links to the user\'s avatars
 * @export
 * @interface UserAvatars
 */
export interface UserAvatars {
  /**
   *
   * @type {string}
   * @memberof UserAvatars
   */
  urlToSize20?: string;
  /**
   *
   * @type {string}
   * @memberof UserAvatars
   */
  urlToSize28?: string;
  /**
   *
   * @type {string}
   * @memberof UserAvatars
   */
  urlToSize32?: string;
  /**
   *
   * @type {string}
   * @memberof UserAvatars
   */
  urlToSize40?: string;
  /**
   *
   * @type {string}
   * @memberof UserAvatars
   */
  urlToSize56?: string;
  /**
   *
   * @type {string}
   * @memberof UserAvatars
   */
  urlToSize64?: string;
  /**
   *
   * @type {string}
   * @memberof UserAvatars
   */
  urlToSize80?: string;
}
