/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { VcsLabel } from './vcs-label';

/**
 * Represents a list of VcsLabel entities.
 * @export
 * @interface VcsLabels
 */
export interface VcsLabels {
  /**
   * The current number of VcsLabel objects in this list.
   * @type {number}
   * @memberof VcsLabels
   */
  count?: number;
  /**
   * The list of VcsLabels owned by this collection that satisfy the given locator.
   * @type {Array<VcsLabel>}
   * @memberof VcsLabels
   */
  vcsLabel?: Array<VcsLabel>;
}
