/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { VcsRoot } from './vcs-root';

/**
 * A VCS root attached to a configuration coupled with this configuration\'s checkout rules.
 * @export
 * @interface VcsRootEntry
 */
export interface VcsRootEntry {
  /**
   * The ID of the attached VCS root.
   * @type {string}
   * @memberof VcsRootEntry
   */
  id?: string;
  /**
   * This is the internal property and is not intented to be used.
   * @type {boolean}
   * @memberof VcsRootEntry
   */
  inherited?: boolean;
  /**
   *
   * @type {VcsRoot}
   * @memberof VcsRootEntry
   */
  'vcs-root'?: VcsRoot;
  /**
   * Checkout rules that allow configurations to partially checkout remote repositories.
   * @type {string}
   * @memberof VcsRootEntry
   */
  'checkout-rules'?: string;
}
