/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents a Versioned Settings Token.
 * @export
 * @interface VersionedSettingsToken
 */
export interface VersionedSettingsToken {
  /**
   *
   * @type {string}
   * @memberof VersionedSettingsToken
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof VersionedSettingsToken
   */
  value?: string;
  /**
   *
   * @type {string}
   * @memberof VersionedSettingsToken
   */
  description?: string;
}
