/* tslint:disable */
/* eslint-disable */
/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { VersionedSettingsError } from './versioned-settings-error';

/**
 * Represents a Versioned Settings Status.
 * @export
 * @interface VersionedSettingsStatus
 */
export interface VersionedSettingsStatus {
  /**
   *
   * @type {boolean}
   * @memberof VersionedSettingsStatus
   */
  dslOutdated?: boolean;
  /**
   *
   * @type {Array<string>}
   * @memberof VersionedSettingsStatus
   */
  missingContextParameters?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof VersionedSettingsStatus
   */
  message?: string;
  /**
   *
   * @type {string}
   * @memberof VersionedSettingsStatus
   */
  type?: VersionedSettingsStatusTypeEnum;
  /**
   *
   * @type {string}
   * @memberof VersionedSettingsStatus
   */
  timestamp?: string;
  /**
   *
   * @type {Array<VersionedSettingsError>}
   * @memberof VersionedSettingsStatus
   */
  versionedSettingsError?: Array<VersionedSettingsError>;
}

export const VersionedSettingsStatusTypeEnum = {
  Info: 'info',
  Warn: 'warn',
} as const;

export type VersionedSettingsStatusTypeEnum =
  (typeof VersionedSettingsStatusTypeEnum)[keyof typeof VersionedSettingsStatusTypeEnum];
