name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint:
    name: Lint (no fix)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - run: npm ci
      - run: npm run lint:check

  format:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - run: npm ci
      - run: npm run format:check

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - run: npm ci
      - run: npm run typecheck

  tests:
    name: Tests with coverage (unit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - run: npm ci
      - name: Run tests with coverage (unit-only + JUnit)
        env:
          JEST_JUNIT_OUTPUT: ./coverage/junit.xml
          JEST_JUNIT_CLASSNAME: "{filepath}"
        run: npm run test:coverage:ci -- --reporters=default --reporters=jest-junit
      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
          if-no-files-found: ignore

  aggregate:
    name: Lint, Typecheck, Test (Node 20)
    runs-on: ubuntu-latest
    needs: [lint, format, typecheck, tests]
    if: always()
    steps:
      - name: Evaluate job results
        run: |
          echo "lint: ${{ needs.lint.result }}"
          echo "format: ${{ needs.format.result }}"
          echo "typecheck: ${{ needs.typecheck.result }}"
          echo "tests: ${{ needs.tests.result }}"
          if [ "${{ needs.lint.result }}" != "success" ] || \
             [ "${{ needs.format.result }}" != "success" ] || \
             [ "${{ needs.typecheck.result }}" != "success" ] || \
             [ "${{ needs.tests.result }}" != "success" ]; then
            echo "One or more jobs failed";
            exit 1;
          fi
