name: Release Please

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    concurrency:
      group: release-please
      cancel-in-progress: true
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
          # Use a PAT so pushes/PRs from this action trigger CI workflows
          # Create a repo secret `RELEASE_PLEASE_TOKEN` with `repo` scope (or fine-grained equivalent)
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
